### ISSUE TITLE
Can't build solution

### ISSUE THREAD

**Issue by aFrontendDev** [buildingblocks/bb-prototype-website-razor#6] opened 2017-01-16 09:54 UTC
OSX Sierra
Without project.json file
dotnet run produces the following:

MAC01-ABLACK:bb-prototype-website-razor ablackledge$ dotnet run
Project bb-prototype-website-razor (.NETCoreApp,Version=v1.1) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
Compiling bb-prototype-website-razor for .NETCoreApp,Version=v1.1
npm WARN package.json path@0.12.7 path is also the name of a node core module.

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:13.7574600
 (The compilation time can be improved. Run "dotnet build --build-profile" for more information)

Unhandled Exception: System.ArgumentException: The directory name /Users/ablackledge/Sites/bb-prototype-website-razor/dist/ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at bb_prototype_website_razor.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in /Users/ablackledge/Sites/bb-prototype-website-razor/Startup.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at bb_prototype_website_razor.Program.Main(String[] args) in /Users/ablackledge/Sites/bb-prototype-website-razor/Program.cs:line 20

**Comment by rsleggett** [comment] 2017-01-16 23:20
@grumpydev22 Try getting the latest version - the problem was gulp was not running before the build. I've fixed this by adding the "gulp" command to the precompile scripts in project.json.

If this works, close this issue 👍

**Comment by jordanrobinson** [comment] 2017-02-17 16:24
Confirmed working.

**Closed as completed by jordanrobinson** 2017-02-17 16:24 UTC
Labels: bug
